// =============================================================
// Module      : instr_mem
// Description : Instruction Memory for IF stage.
//               - Instructions are always 32-bit, regardless of the
//                 64-bit datapath width elsewhere in the design.
//               - Addressed by a 64-bit byte address (the PC), but
//                 only enough low bits are used to index the array;
//                 MIPS instructions are always word-aligned (addr[1:0]
//                 must be 00 -- not enforced here, assumed by design).
//               - Combinational read: required so the fetched
//                 instruction is valid within the same cycle the
//                 address is presented, before IF/ID latches it.
//               - Depth is parameterized (default 1024 words = 4KB).
//               - Loaded via $readmemh from a hex file generated by
//                 our assembler (scripts/assembler.py).
// =============================================================

module instr_mem #(
    parameter MEM_DEPTH_WORDS = 1024,                       // # of 32-bit words
    parameter ADDR_BITS       = $clog2(MEM_DEPTH_WORDS)     // bits needed to index
) (
    input  wire [63:0] addr,          // byte address (from PC)
    output wire [31:0] instr_out      // fetched instruction
);

    reg [31:0] mem [0:MEM_DEPTH_WORDS-1];
    integer i;

    // Word-index = byte address >> 2, truncated to ADDR_BITS.
    wire [ADDR_BITS-1:0] word_idx = addr[ADDR_BITS+1:2];

    assign instr_out = mem[word_idx];

    // Program load: expects a hex file with one 32-bit instruction
    // per line, e.g. produced by scripts/assembler.py.
    // NOTE: $readmemh path is relative to Vivado's simulation working
    // directory (typically <project>.sim/sim_1/behav/xsim/), NOT the
    // project root. See project README / chat notes for how to point
    // this at your actual hex file location.
    initial begin
        for (i = 0; i < MEM_DEPTH_WORDS; i = i + 1)
            mem[i] = 32'h00000000; // NOP-fill (opcode 0, funct 0 = sll $0,$0,0)
        $readmemh("C:/Users/shrey/fpga_implementation/MIPS 64 Pipeline Architecture/sw/hex/program.hex", mem);
    end

endmodule
